import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as XLSX from 'xlsx';
import './styles.css';

type Frequency = { term: string; count: number; first: number };
type CsvData = { name: string; headers: string[]; rows: string[][]; error?: string };
const STOPWORDS = new Set('a an and are as at be by for from has have he her his i in is it its me my of on or our she that the their them they this to was we were what when where which who will with you your 的 了 和 是 在 我 有 也 就 不 人 都 一个 这 他 她 它 们 为 之 与 而 及 或 被 对 到 从 以 于'.split(' '));

function tokenize(text: string) { return text.match(/[A-Za-zÀ-ÖØ-öø-ÿ0-9]+|[一-龥]+/gu) ?? []; }
function isNumber(t: string) { return /^[\d０-９]+([.,，．]\d+)?%?$/.test(t); }
function makeFreq(tokens: string[], n: number, ignoreCase: boolean, excludeStop = false, excludeNumber = false): Frequency[] {
  const map = new Map<string, Frequency>();
  for (let i = 0; i <= tokens.length - n; i++) {
    const part = tokens.slice(i, i + n); const raw = part.join(n === 1 ? '' : ' '); const key = ignoreCase ? raw.toLocaleLowerCase() : raw;
    if (n === 1 && ((excludeStop && STOPWORDS.has(key)) || (excludeNumber && isNumber(key)))) continue;
    const old = map.get(key); if (old) old.count++; else map.set(key, { term: raw, count: 1, first: i });
  }
  return [...map.values()].sort((a, b) => b.count - a.count || a.first - b.first);
}
function csvParse(buffer: ArrayBuffer): CsvData { 
  const bytes = new Uint8Array(buffer); const utf = new TextDecoder('utf-8').decode(bytes); const text = utf.includes('�') ? new TextDecoder('gb18030').decode(bytes) : utf;
  const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/).filter((x) => x.length > 0); if (!lines.length) return { name: '', headers: [], rows: [] };
  const delimiter = (lines[0].match(/;/g)?.length ?? 0) > (lines[0].match(/,/g)?.length ?? 0) ? ';' : ',';
  const parse = (line: string) => { const out: string[] = []; let cell = '', quoted = false; for (let i = 0; i < line.length; i++) { const c = line[i]; if (c === '"' && line[i + 1] === '"') { cell += '"'; i++; } else if (c === '"') quoted = !quoted; else if (c === delimiter && !quoted) { out.push(cell); cell = ''; } else cell += c; } out.push(cell); return out; };
  const parsed = lines.map(parse); const scanLimit = Math.min(20, Math.max(1, parsed.length - 1)); let headerIndex = 0; let bestScore = -Infinity; for (let i = 0; i < scanLimit; i++) { const row = parsed[i].map((v) => v.trim()).filter(Boolean); const next = parsed[i + 1] ?? []; const nextNext = parsed[i + 2] ?? []; const unique = new Set(row).size; const numeric = row.filter((v) => /^[\d.,%+-]+$/.test(v)).length; const score = row.length * 3 + unique * 2 + (Math.abs(next.length - parsed[i].length) <= 1 ? 4 : 0) + (Math.abs(nextNext.length - parsed[i].length) <= 1 ? 2 : 0) - numeric * 2 - (parsed[i].length === 1 ? 5 : 0) - i * 0.05; if (score > bestScore) { bestScore = score; headerIndex = i; } } const headers = parsed[headerIndex].map((h, i) => h.trim() || "未命名列" + (i + 1)); return { name: "", headers, rows: parsed.slice(headerIndex + 1) };
}
function cleanSheetName(name: string, used: Set<string>) { let base = name.replace(/[\\/?*\[\]:]/g, ' ').trim().slice(0, 31) || '未命名'; let out = base; let n = 2; while (used.has(out)) { const suffix = `_${n++}`; out = base.slice(0, 31 - suffix.length) + suffix; } used.add(out); return out; }

function App() {
  const [texts, setTexts] = useState<string[]>(() => { try { const saved = JSON.parse(localStorage.getItem('vw-texts') ?? 'null'); if (Array.isArray(saved)) return [...saved.slice(0, 10), ...Array(Math.max(0, 10 - saved.length)).fill('')].slice(0, 10); } catch {} return [localStorage.getItem('vw-text') ?? '', ...Array(9).fill('')]; }); const [enabledTextTabs, setEnabledTextTabs] = useState<boolean[]>(() => { try { const saved = JSON.parse(localStorage.getItem('vw-enabled-text-tabs') ?? 'null'); if (Array.isArray(saved)) return [...saved.slice(0, 10), ...Array(Math.max(0, 10 - saved.length)).fill(true)].slice(0, 10).map(Boolean); } catch {} return Array(10).fill(true); }); const [activeTextTab, setActiveTextTab] = useState(0); const text = texts[activeTextTab] ?? ''; const setText = (value: string) => setTexts((previous) => previous.map((item, index) => index === activeTextTab ? value : item)); const [mainTerms, setMainTerms] = useState<string[]>(() => JSON.parse(localStorage.getItem('vw-main') ?? '[]')); const [otherTerms, setOtherTerms] = useState<string[]>(() => JSON.parse(localStorage.getItem('vw-other') ?? '[]'));
  const [limit, setLimit] = useState(10); const [statWordCount, setStatWordCount] = useState(0); const [pageDraft, setPageDraft] = useState('1'); const [activeFrequency, setActiveFrequency] = useState<'one'|'two'|'custom'>('one'); const [frequencyPage, setFrequencyPage] = useState(1); const [ngram, setNgram] = useState(3); const [ignoreCase, setIgnoreCase] = useState(false); const [excludeStop, setExcludeStop] = useState(false); const [excludeNumber, setExcludeNumber] = useState(false); const [stats, setStats] = useState<{one: Frequency[]; two: Frequency[]; custom: Frequency[]}>({ one: [], two: [], custom: [] });
  const [files, setFiles] = useState<CsvData[]>([]); const [selectedColumns, setSelectedColumns] = useState<string[]>([]); const [isDraggingFiles, setIsDraggingFiles] = useState(false); const [warningMessage, setWarningMessage] = useState<string | null>(null); const [warningContinue, setWarningContinue] = useState<(() => void) | null>(null); const [confirmAction, setConfirmAction] = useState<{title: string; message: string; action: () => void} | null>(null); const dragDepth = useRef(0); const [column, setColumn] = useState(''); const [status, setStatus] = useState(''); const [downloadReady, setDownloadReady] = useState(false); const history = useRef<string[]>([]); const historyIndex = useRef(-1);
  useEffect(() => localStorage.setItem('vw-texts', JSON.stringify(texts)), [texts]); useEffect(() => localStorage.setItem('vw-enabled-text-tabs', JSON.stringify(enabledTextTabs)), [enabledTextTabs]); useEffect(() => localStorage.setItem('vw-main', JSON.stringify(mainTerms)), [mainTerms]); useEffect(() => localStorage.setItem('vw-other', JSON.stringify(otherTerms)), [otherTerms]); useEffect(() => { if (!files.length && column) setColumn(''); }, [files.length, column]); useEffect(() => { const hasFiles = (event: DragEvent) => Boolean(event.dataTransfer?.types?.includes('Files')); const onEnter = (event: DragEvent) => { if (!hasFiles(event)) return; event.preventDefault(); dragDepth.current += 1; setIsDraggingFiles(true); }; const onOver = (event: DragEvent) => { if (hasFiles(event)) event.preventDefault(); }; const onLeave = (event: DragEvent) => { if (!hasFiles(event)) return; event.preventDefault(); dragDepth.current = Math.max(0, dragDepth.current - 1); if (dragDepth.current === 0) setIsDraggingFiles(false); }; const onDrop = (event: DragEvent) => { if (!hasFiles(event)) return; event.preventDefault(); dragDepth.current = 0; setIsDraggingFiles(false); if (event.dataTransfer?.files.length) upload(event.dataTransfer.files); }; window.addEventListener('dragenter', onEnter); window.addEventListener('dragover', onOver); window.addEventListener('dragleave', onLeave); window.addEventListener('drop', onDrop); return () => { window.removeEventListener('dragenter', onEnter); window.removeEventListener('dragover', onOver); window.removeEventListener('dragleave', onLeave); window.removeEventListener('drop', onDrop); }; }, []);
  const combinedText = texts.filter((value, index) => enabledTextTabs[index] && value).join("\n"); const tokens = useMemo(() => tokenize(combinedText), [combinedText]); const counts = { chars: [...combinedText].length, words: tokens.length, sentences: combinedText ? (combinedText.match(/[。！？!?\.]+|\n+/g)?.length ?? 1) : 0 };
  const changeText = (value: string) => { if (value !== text) { history.current = history.current.slice(0, historyIndex.current + 1); history.current.push(text); historyIndex.current++; setText(value); } };
  const undo = () => { if (historyIndex.current >= 0) { setText(history.current[historyIndex.current]); historyIndex.current--; } }; const redo = () => { const next = historyIndex.current + 1; if (next < history.current.length) { setText(history.current[next]); historyIndex.current = next; } };
  const clearText = () => { if (text) setConfirmAction({ title: '清空当前页签文本', message: '确定清空当前页签的文本吗？可以使用撤销恢复。', action: () => changeText('') }); }; const clearAllTexts = () => { if (texts.some(Boolean)) setConfirmAction({ title: '清空全部页签文本', message: '确定清空全部 10 个页签的文本吗？此操作会清除所有页签内容。', action: () => setTexts(Array(10).fill('')) }); };
  const calculate = () => { setStats({ one: makeFreq(tokens, 1, ignoreCase, excludeStop, excludeNumber), two: makeFreq(tokens, 2, ignoreCase), custom: makeFreq(tokens, ngram, ignoreCase) }); setStatWordCount(tokens.length); setFrequencyPage(1); };
  const frequencyData = stats[activeFrequency]; const frequencyPages = Math.max(1, Math.ceil(frequencyData.length / limit)); const frequencyStart = (frequencyPage - 1) * limit; useEffect(() => setPageDraft(String(frequencyPage)), [frequencyPage]);
  const addTerm = (term: string, kind: 'main' | 'other') => { const setter = kind === 'main' ? setMainTerms : setOtherTerms; setter((items) => items.includes(term) ? items : [...items, term]); }; const toggleTerm = (term: string, kind: 'main' | 'other') => { const setter = kind === 'main' ? setMainTerms : setOtherTerms; setter((items) => items.includes(term) ? items.filter((item) => item !== term) : [...items, term]); };
  const [manual, setManual] = useState({ main: '', other: '' }); const addManual = (kind: 'main' | 'other') => { const v = manual[kind].trim(); if (v) { addTerm(v, kind); setManual({ ...manual, [kind]: '' }); } };
  const move = (kind: 'main' | 'other', i: number, dir: -1 | 1) => { const arr = [...(kind === 'main' ? mainTerms : otherTerms)]; const j = i + dir; if (j < 0 || j >= arr.length) return; [arr[i], arr[j]] = [arr[j], arr[i]]; (kind === 'main' ? setMainTerms : setOtherTerms)(arr); };
  const upload = async (list: FileList | null) => { if (!list) return; const parsed: CsvData[] = []; for (const file of Array.from(list)) { try { const d = csvParse(await file.arrayBuffer()); parsed.push({ ...d, name: file.name }); } catch { parsed.push({ name: file.name, headers: [], rows: [], error: '解析失败' }); } } setFiles((previous) => [...previous, ...parsed]); const cols = [...new Set(parsed.flatMap(f => f.headers))]; setSelectedColumns((previous) => [...previous, ...cols.filter((col) => !previous.includes(col))]); setStatus(`已读取 ${parsed.length} 个文件，共 ${parsed.reduce((n, f) => n + f.rows.length, 0)} 行`); };
  const buildWorkbook = (force = false) => { if (!files.length || !column) { setStatus('请先上传 CSV 并选择检索列'); return; } if (!mainTerms.length && !otherTerms.length && !force) { setWarningMessage('主词条和其他词条都为空，继续后将只生成主页签。'); setWarningContinue(() => () => buildWorkbook(true)); return; } const valid = files.filter(f => f.headers.includes(column)); const headers = [...new Set(valid.flatMap(f => f.headers))]; const exportHeaders = headers.filter((header) => selectedColumns.includes(header)); const all = valid.flatMap(f => f.rows.map(r => Object.fromEntries(headers.map(h => [h, r[f.headers.indexOf(h)] ?? ''])))); const wb = XLSX.utils.book_new(); const used = new Set<string>(); const add = (name: string, rows: Record<string, string>[]) => { const outputRows = rows.map(row => Object.fromEntries(exportHeaders.map(header => [header, row[header] ?? '']))); const ws = XLSX.utils.json_to_sheet(outputRows.length ? outputRows : [Object.fromEntries(exportHeaders.map(h => [h, '']))], { header: exportHeaders }); XLSX.utils.book_append_sheet(wb, ws, cleanSheetName(name, used)); }; add('主页签', all); mainTerms.forEach(term => add(term, all.filter(r => String(r[column]).toLocaleLowerCase().includes(term.toLocaleLowerCase())))); const other = all.filter(r => otherTerms.some(term => String(r[column]).toLocaleLowerCase().includes(term.toLocaleLowerCase()))); add('其他', other); XLSX.writeFile(wb, `词频汇总_${new Date().toISOString().slice(0, 10)}.xlsx`); setDownloadReady(true); setStatus(`筛选完成：${valid.length} 个文件，主页签 ${all.length} 行`); };
  return <main>{warningMessage && <div className="modal-backdrop" role="presentation"><div className="confirm-dialog warning-dialog" role="dialog" aria-modal="true" aria-labelledby="warning-title"><h3 id="warning-title">词条为空</h3><p>{warningMessage}</p><div className="confirm-actions"><button onClick={() => { setWarningMessage(null); setWarningContinue(null); }}>返回</button><button className="primary" onClick={() => { const next = warningContinue; setWarningMessage(null); setWarningContinue(null); next?.(); }}>继续</button></div></div></div>}{confirmAction && <div className="modal-backdrop" role="presentation"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h3 id="confirm-title">{confirmAction.title}</h3><p>{confirmAction.message}</p><div className="confirm-actions"><button onClick={() => setConfirmAction(null)}>取消</button><button className="primary" onClick={() => { confirmAction.action(); setConfirmAction(null); }}>确认清空</button></div></div></div>}{isDraggingFiles && <div className="drag-overlay" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); e.stopPropagation(); dragDepth.current = 0; setIsDraggingFiles(false); if (e.dataTransfer.files.length) upload(e.dataTransfer.files); }}><div className="drag-overlay-card"><span>↓</span><strong>释放文件以导入 CSV</strong><small>支持一次拖入多个文件，已有文件会保留</small></div></div>}<header><div><span className="eyebrow">VOCABULARY WORKBENCH</span><h1>词频整理工作台</h1><p>把文本里的高频词，整理成可复用的词库和数据表。</p></div><div className="privacy">⌁ 本地处理 · 数据不上传</div></header>
    <section className="stats"><div><small>字符数</small><strong>{counts.chars.toLocaleString()}</strong></div><div><small>单词数</small><strong>{counts.words.toLocaleString()}</strong></div><div><small>句子数</small><strong>{counts.sentences.toLocaleString()}</strong></div></section>
    <div className="grid"><section className="panel editor"><div className="section-head"><div><span className="kicker">01 / INPUT</span><h2>输入文本</h2></div><div className="actions"><button onClick={undo} disabled={historyIndex.current < 0} title={historyIndex.current < 0 ? "没有可撤销的文本操作" : ""}>撤销</button><button className="ghost danger" onClick={clearText} disabled={!text} title={!text ? "当前没有文本可清空" : ""}>清空</button><button className="clear-all" onClick={clearAllTexts} disabled={!texts.some(Boolean)} title={!texts.some(Boolean) ? "当前没有任何页签内容可清空" : ""}>清空全部页签</button></div></div><div className="text-tabs">{texts.map((_, index) => <div className="text-tab" key={index}><button className={activeTextTab === index ? "active" : ""} onClick={() => setActiveTextTab(index)}>页签 {index + 1}</button><button type="button" className={`text-tab-toggle ${enabledTextTabs[index] ? "enabled" : "disabled"}`} title={enabledTextTabs[index] ? "点击关闭此页签统计" : "点击开启此页签统计"} onClick={() => setEnabledTextTabs(previous => previous.map((enabled, i) => i === index ? !enabled : enabled))}>{enabledTextTabs[index] ? "统计中" : "已关闭"}</button></div>)}</div><textarea value={text} onChange={e => changeText(e.target.value)} placeholder="粘贴或输入一大段文本…" /><div className="toolbar"><button className="primary" onClick={calculate}>开始统计 <span>→</span></button><label>每页显示 <select value={limit} onChange={e => { setLimit(Number(e.target.value)); setFrequencyPage(1); }}><option value={10}>10 条</option><option value={15}>15 条</option><option value={20}>20 条</option><option value={30}>30 条</option><option value={50}>50 条</option></select></label><label>自定义词数 <select value={ngram} onChange={e => setNgram(Number(e.target.value))}>{Array.from({length: 8}, (_, i) => <option key={i} value={i + 3}>{i + 3} 词</option>)}</select></label></div><div className="switches"><label><input type="checkbox" checked={excludeStop} onChange={e => setExcludeStop(e.target.checked)} /> 排除语法词 <span>仅影响 1 词</span></label><label><input type="checkbox" checked={excludeNumber} onChange={e => setExcludeNumber(e.target.checked)} /> 排除数字词 <span>仅影响 1 词</span></label><label><input type="checkbox" checked={ignoreCase} onChange={e => setIgnoreCase(e.target.checked)} /> 忽略大小写</label></div></section>
      <section className="panel results"><div className="section-head"><div><span className="kicker">02 / FREQUENCY</span><h2>词频结果</h2></div><span className="muted">点击单条结果即可添加</span></div><div className="freq-tabs"><button className={activeFrequency === "one" ? "active" : ""} onClick={() => {setActiveFrequency("one"); setFrequencyPage(1)}}>1 词 <span>{stats.one.length}</span></button><button className={activeFrequency === "two" ? "active" : ""} onClick={() => {setActiveFrequency("two"); setFrequencyPage(1)}}>2 词 <span>{stats.two.length}</span></button><button className={activeFrequency === "custom" ? "active" : ""} onClick={() => {setActiveFrequency("custom"); setFrequencyPage(1)}}>{ngram} 词 <span>{stats.custom.length}</span></button></div><FrequencyGroup title={activeFrequency === "one" ? "1 词" : activeFrequency === "two" ? "2 词" : ngram + " 词"} data={frequencyData.slice(frequencyStart, frequencyStart + limit)} total={frequencyData.length} offset={frequencyStart} limit={limit} denominator={statWordCount} main={mainTerms} other={otherTerms} addTerm={toggleTerm} /><div className="pagination"><button onClick={() => setFrequencyPage(p => Math.max(1, p - 1))} disabled={frequencyPage <= 1} title={frequencyPage <= 1 ? "已经是第一页" : ""}>← 上一页</button><span className="page-jump"><span>第</span><input className="page-input" type="number" min="1" max={frequencyPages} value={pageDraft} onChange={e => setPageDraft(e.target.value)} onKeyDown={e => { if (e.key === "Enter") { const page = Math.min(frequencyPages, Math.max(1, Number(pageDraft) || 1)); setFrequencyPage(page); } }} /><span>/ {frequencyPages} 页</span><button onClick={() => { const page = Math.min(frequencyPages, Math.max(1, Number(pageDraft) || 1)); setFrequencyPage(page); }}>跳转</button></span><button onClick={() => setFrequencyPage(p => Math.min(frequencyPages, p + 1))} disabled={frequencyPage >= frequencyPages} title={frequencyPage >= frequencyPages ? "已经是最后一页" : ""}>下一页 →</button></div></section></div>
    <section className="panel terms-panel"><div className="section-head"><div><span className="kicker">03 / VOCABULARY</span><h2>词条栏位</h2></div><span className="muted">可拖拽或用箭头排序</span></div><div className="term-columns"><TermColumn title="主词条" terms={mainTerms} kind="main" manual={manual.main} setManual={v => setManual({...manual, main: v})} addManual={addManual} setTerms={setMainTerms} move={move} onClear={() => setConfirmAction({ title: "清空主词条", message: "确定清空主词条栏位吗？", action: () => setMainTerms([]) })}/><TermColumn title="其他" terms={otherTerms} kind="other" manual={manual.other} setManual={v => setManual({...manual, other: v})} addManual={addManual} setTerms={setOtherTerms} move={move} onClear={() => setConfirmAction({ title: "清空其他词条", message: "确定清空其他词条栏位吗？", action: () => setOtherTerms([]) })}/></div></section>
    <section className="panel csv-panel"><div className="section-head"><div><span className="kicker">04 / CSV → EXCEL</span><h2>数据汇总</h2></div><div className="csv-actions"><label className="upload"><input type="file" accept=".csv,text/csv" multiple onChange={e => upload(e.target.files)} />＋ 上传多个 CSV</label><button className="ghost danger" onClick={() => files.length && setConfirmAction({ title: "清空已上传文件", message: "确定清空所有已上传的 CSV 文件吗？", action: () => { setFiles([]); setSelectedColumns([]); setColumn(""); setDownloadReady(false); setStatus(""); } })} disabled={!files.length} title={!files.length ? "当前没有已上传的 CSV 文件" : ""}>清空</button></div></div><div className="csv-controls"><label>所有文件使用的检索列<select value={column} onChange={e => setColumn(e.target.value)} disabled={!files.length}><option value="">请选择列名</option>{[...new Set(files.flatMap(f => f.headers))].map(c => <option key={c}>{c}</option>)}</select></label><button className="primary" onClick={() => buildWorkbook()} disabled={!files.length || !column} title={!files.length ? "请先上传 CSV 文件" : !column ? "请先选择检索列" : ""}>开始筛选并下载 <span>↓</span></button></div>{files.length ? <div className="column-picker"><div className="column-picker-head"><b>导出数据列</b><div><button onClick={() => setSelectedColumns([...new Set(files.flatMap(f => f.headers))])}>全选</button><button onClick={() => setSelectedColumns([])}>清空</button></div></div><div className="column-options">{[...new Set(files.flatMap(f => f.headers))].map(header => <label key={header}><input type="checkbox" checked={selectedColumns.includes(header)} onChange={() => setSelectedColumns(selectedColumns.includes(header) ? selectedColumns.filter(col => col !== header) : [...selectedColumns, header])} />{header}</label>)}</div></div> : null}{files.length ? <div className="files">{files.map((f, i) => <div className="file" key={f.name + "-" + i}><span>▤</span><div><b>{f.name}</b><small>{f.error ?? (f.rows.length + " 行 · " + f.headers.length + " 列")}</small></div><button className="file-remove" onClick={() => setFiles(files.filter((_, index) => index !== i))} aria-label="删除文件">×</button></div>)}</div> : null}<div className="dropzone" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); e.stopPropagation(); upload(e.dataTransfer.files); }}>拖入一个或多个 CSV 文件，或点击上方按钮选择文件</div><p className="status">{status || (downloadReady ? '文件已下载' : '筛选结果将生成主页签、主词条页签和其他页签')}</p></section>
    <footer>词频整理工作台 <span>·</span> 轻量、私密、在你的浏览器里完成</footer></main>;
}

function FrequencyGroup({title,data,total,offset,denominator,main,other,addTerm}:{title:string;data:Frequency[];total:number;offset:number;limit:number;denominator:number;main:string[];other:string[];addTerm:(t:string,k:"main"|"other")=>void}) { return <div className="freq"><div className="freq-title"><b>{title}</b><span>{total ? (offset + 1) + "–" + (offset + data.length) + " / " + total : "暂无结果"}</span></div>{data.map((x,i)=><div className="freq-row" key={x.term + "-" + (offset+i)}><em>{String(offset + i + 1).padStart(2,"0")}</em><strong className={title === "1 词" ? "" : "phrase-term"}>{x.term}</strong><small className="frequency-meta"><span className="count-value"><b>{x.count}</b> 次</span><span className="meta-divider">·</span><span className="percent-value"><b>{(x.count / Math.max(1, denominator)*100).toFixed(1)}</b>%</span></small><button className={"term-action main-action " + (main.includes(x.term) ? "added" : "")} onClick={() => addTerm(x.term,"main")}>{main.includes(x.term)?"✓ 主词条":"主词条"}</button><button className={"term-action other-action " + (other.includes(x.term) ? "added" : "")} onClick={() => addTerm(x.term,"other")}>{other.includes(x.term)?"✓ 其他":"其他"}</button></div>)}</div> }function TermColumn({title,terms,kind,manual,setManual,addManual,setTerms,move,onClear}:{title:string;terms:string[];kind:'main'|'other';manual:string;setManual:(v:string)=>void;addManual:(k:'main'|'other')=>void;setTerms:(v:string[])=>void;move:(k:'main'|'other',i:number,d:-1|1)=>void;onClear:()=>void}) { return <div className="term-column"><div className="term-head"><h3>{title}</h3><button className="ghost danger" onClick={onClear} disabled={!terms.length} title={!terms.length ? "当前栏位没有词条可清空" : ""}>清空</button></div><div className="manual"><input value={manual} onChange={e=>setManual(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addManual(kind)} placeholder={`添加${title}词条…`} /><button onClick={()=>addManual(kind)}>添加</button></div><div className="term-list">{terms.length ? terms.map((t,i)=><div className="term" draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{const from=Number(e.dataTransfer.getData('text/plain')); const a=[...terms]; const [v]=a.splice(from,1); a.splice(i,0,v); setTerms(a)}} key={t}><span className="handle">⠿</span><span>{t}</span><button onClick={()=>move(kind,i,-1)} aria-label="上移">↑</button><button onClick={()=>move(kind,i,1)} aria-label="下移">↓</button><button className="remove" onClick={()=>setTerms(terms.filter(x=>x!==t))}>×</button></div>) : <div className="empty">还没有词条<br/><small>从右侧词频结果一键添加</small></div>}</div></div> }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
